### PR TITLE
Channel splitting

### PR DESCRIPTION
**Pull request by luckysori**

### CODE REVIEW

**Comment by luckysori** [comment]
@Tibo-lg: I've finally created the draft PR I mentioned. I had to update the fork's `main` to 0.0.116, so that we get a useful diff here.

**Comment by Tibo-lg** [comment]
That's awesome thanks!

**Comment by luckysori** [comment]
I've [squashed](https://github.com/p2pderivatives/rust-lightning/pull/11/commits/9a9cecda8f86f667572efc61a47dce6bb9409d94) the fixup and removed the merge commit in the process since we don't even want it.

I'll open a PR to update `rust-dlc` to the tip of this branch.

**Comment by Tibo-lg** [comment]
Looks like something's wrong with the build?

**Comment by luckysori** [comment]
> Looks like something's wrong with the build?

I don't think so. We just get warnings because of all the things that are not linted properly in LDK, right?

**Comment by Tibo-lg** [comment]
The build used to pass at least AFAIR

**Comment by Tibo-lg** [comment]
> The build used to pass at least AFAIR

Never mind, the build works but not after rebase so it's the same as before sorry.

**Comment by luckysori** [comment]
Superseded by #13 to use a differently named branch: `split-tx-experiment`.

**Pull request closed without merging**
